### ISSUE TITLE
Cucumber report feature uri problem

### ISSUE THREAD

**Issue by akhadija** [cukespace/cukespace#101]
I have a problem with generated cucumber reports when it is RunWith(CukeSpace.class)
Im expecting the names of features as shown in the picture below:

![slack2](https://user-images.githubusercontent.com/26091047/27484754-edb14d22-5819-11e7-94ff-de01db19776d.PNG)

but i have just the same uri for all features and all reports result in Jenkins point to the last one:

![slack_notif_ko](https://user-images.githubusercontent.com/26091047/27484660-8b369c06-5819-11e7-9bfd-0c5ab71b364b.PNG)

**Comment by rmannibucau** [comment]
Hi

did you investigated the dump files, in particular the json output? Also a small github project all setup to reproduce would probably help

**Comment by akhadija** [comment]
Yes the uri in the json file is the same for all features "uri": "src/test/java/features/" 
Here is a github project to reproduce the problem:
https://github.com/akhadija/cucumber_arquillian

**Comment by rmannibucau** [comment]
last commit should have fixed it

**Comment by akhadija** [comment]
Yes it's fixed thank you @rmannibucau
