### ISSUE TITLE
split core?

### ISSUE THREAD

**Issue by toepi** [cukespace/cukespace#116]
question, before I create a pull request. 

Will you accept a pull request with split core into multiple parts?

Background: We will usw arquillian-junit-standalone for ours e2e-tests. after looking at your code I think it only works with arquillian-*-container, so I think it will be better to have cuke-core, cuke-container and so one ...

If you ask me I would also separate testing and junit.

What do you think about this idea?

**Comment by rmannibucau** [comment]
Before digging: There is a standalone container so it should work like that AFAIK. Do you hit any blocker?

**Comment by toepi** [comment]
I have only remove the container-dependencies and have found some compiler errors, in the extensions so I think it will not work, after my Arquillian understanding, core should load all extensions. I'll test it, an if it works okay.  And for me core has a lot dependencies. Okay all do an amazing job but cukedoctor if I only want execute bdd? Not understand me wrong I like cukedoctor and use it!

**Comment by rmannibucau** [comment]
I get it. Same on my side, im not against a split but I think it is not needed to use cukespace so I would like to check where we failed before working on anything. We can move several deps as being provided and i think it is ok to use standalone container. Maybe let's start from there with some sample project on github?

**Comment by toepi** [comment]
Yeah, you are completely right. Have create a very small project and arquillian start without any deployment-method. Thank and sorry for the noise.
