### ISSUE TITLE
AfterStep event is never triggered when using an Arquillian observer

### ISSUE THREAD

**Issue by daniel-a-melo** [cukespace/cukespace#127]
**Symptom**

The event `AfterStep` is never triggered when observed with an Arquillian observer.

TestIT
```java

import org.jboss.arquillian.core.api.annotation.Observer;
import cucumber.runtime.arquillian.CukeSpace;
import cucumber.runtime.arquillian.api.Features;
import cucumber.runtime.arquillian.api.Glues;

@RunWith(CukeSpace.class)
@Observer(EventsObserver.class)
@Features({
        "features/tests.feature",
})
@Glues({
        TestsSteps.class
})
public class TestIT {
}
```

EventsObserver
```java
import org.jboss.arquillian.core.api.annotation.Observes;
import cucumber.runtime.arquillian.api.event.AfterStep;
import cucumber.runtime.arquillian.api.event.BeforeStep;

public class EventsObserver {
    public void observeBeforeStep(@Observes BeforeStep event) {
         System.out.println("BeforeStep");
    }

    public void observeAfterStep(@Observes AfterStep event) {
         System.out.println("AfterStep");
    }
}
````

The event handler for `BeforeStep` is triggered, but the handler for `AfterStep` is never triggered

**Expected behavior**

Both handlers for `BeforeStep` and `AfterStep` would be triggered

**Comment by rmannibucau** [comment]
Hi @daniel-a-melo , can you try on master, AfterStep is now fired with result reporter callback and not after one.

**Comment by daniel-a-melo** [comment]
Hi @rmannibucau . I have just tested on master, and `AfterStep` is not triggered. 

By inspecting `cucumber.runtime.Runtime#runStep` I can see it never calls `gherkin.formatter.Reporter#after`

**Comment by rmannibucau** [comment]
@daniel-a-melo yes, the code moved from after to result in this commit fixing the issue you described: https://github.com/cukespace/cukespace/commit/f47b09a58e3071c8f505c5bdc96548eaa7c7d8ce#diff-059f9bc8c5499a9a1856128ae393223f248d82840c9ac75ec9fca9891717890aR432
Do you have a project reproducing it? Using the examples/ and a LoadableExtension it works well - indeed it is not supported on server side code if remote.

**Comment by daniel-a-melo** [comment]
I am sorry @rmannibucau my mistake. I hadn't realized you have just pushed a fix. 

I can confirm that with master `AfterStep` is now triggered. 

Thanks very much for your support

**Comment by rmannibucau** [comment]
Great, thanks for confirming. Closing then :).
