### ISSUE TITLE
Create configuration handler to manage extension config

### ISSUE THREAD

**Issue by rmpestano** [cukespace/cukespace#58]
Idea is to support easily optional config handling (like yaml)

Here is the proposed API:

    interface ConfigHandler {
        void handle(CucumberConfiguration, ExtensionDef);
    }

The config parser would then read each property and potentially load the handler if it depends on an optional dependency. If it cant be loaded then the exact maven dependency should be logged (to support copy/paste on user experience side).

Default (always working) should use properties syntax but yaml one is nice if we have no dependency conflict with yaml. We can think to a json one too but I dont see the need yet.

**Comment by rmannibucau** [comment]
Is that still needed? think most of reporting can be done like arquillian-asciidoctor-extension without polluting more cukespace (just trying to cleanup a bit issues ;))

**Comment by rmpestano** [comment]
:+1:
