### ISSUE TITLE
cukespace with wildfly 8.2 

### ISSUE THREAD

**Issue by zizigooloo** [cukespace/cukespace#59]
Hi Dear 
I want to use maven cukesapce-core with wildfly 8.2 when used @Deployment to create java archive,
as a result, Error generated: 
java.lang.TypeNotPresentException: Type cucumber.runtime.arquillian.CukeSpace not present
Caused by: java.lang.ClassNotFoundException: cucumber.runtime.arquillian.CukeSpace

 then i change it to maven cukesapce-jbas7 with previous configuration,
as a result, Error generated: 
java.lang.UnsupportedOperationException: JavaArchive spec does not support Libraries

and then deleted @Deployment along with function from test everything is ok.

what's the problem?
thx

**Comment by rmannibucau** [comment]
Hi

Server side tests needs enriching so jar are not supported. Switch to a war and it should work.

**Comment by zizigooloo** [comment]
Hi 
thanks a lot for the response  as soon as possible!!
I 've tried it then solved the problem with changing JavaArchive to WebArchive 
Deployment into wildfly,
but 
i can use JavaArchive deployment with other application servers such as glassfish.

What's your idea about it?

THX

**Comment by rmannibucau** [comment]
If the server is embedded (ie no fork - like tomee-embedded and I think some glassfish adapters) then no issue to use it

**Comment by zizigooloo** [comment]
Hi again
i tried it JavaArchive with wildfly-embedded then it failed.

What's your idea about it?

THX

**Comment by rmannibucau** [comment]
JBoss* uses a OSGi like system (for isolation) so I guess you need to make cukespace and its dependencies available in the application with jboss descriptor.

**Comment by zizigooloo** [comment]
Hi
OK
thanks a lot.
