### ISSUE TITLE
Please publish 1.6.2!

### ISSUE THREAD

**Issue by axelberle** [cukespace/cukespace#68]
I would like to reference the version 1.6.2 in my projects, without needing to build it locally. 
The only change (due to a version conflict) I would suggest is:

```
    <dependency>
      <groupId>commons-collections</groupId>
      <artifactId>commons-collections</artifactId>
      <version>3.2.1</version>
    </dependency>
```

I would like to contribute with some examples running on remote Wildfly, based on this version.

Regards,
Axel

**Comment by axelberle** [comment]
when trying to build the 1.6.2-SNAPSHOT version, the following conflict is reported:

```
[ERROR] 
Dependency convergence error for commons-collections:commons-collections:3.2.1 paths to dependency are:
+-com.github.cukespace:cukespace-core:1.6.2-SNAPSHOT
  +-org.jboss.arquillian.extension:arquillian-persistence-core:1.0.0.Alpha7
    +-org.jboss.arquillian.extension:arquillian-persistence-spi:1.0.0.Alpha7
      +-org.dbunit:dbunit:2.5.0
        +-commons-collections:commons-collections:3.2.1
and
+-com.github.cukespace:cukespace-core:1.6.2-SNAPSHOT
  +-commons-collections:commons-collections:3.2.2
```

**Comment by rmannibucau** [comment]
@axelberle this dependency conflict should be solved but cucmber-java8 has some bug with recent JDK so not sure it should be shipped before

**Comment by axelberle** [comment]
I saw you fixed the conflicts. Merci beaucoup!
