### ISSUE TITLE
Using @RunAsClient in functional tests?

### ISSUE THREAD

**Issue by kulasekp** [cukespace/cukespace#7]
Hi,
is it possible to run functional tests using mixed mode?
The idea is to use "in-container" mode on "Given" step to prepare test data using CDI/EJB beans and then switch to "client mode" to run "When" and "Then".

Or maybe you have another idea how to accomplish it? Thanks!

**Comment by aVolpe** [comment]
@rmannibucau It's still no posible to use `@RunAsClient` with a step? if not, it's possible to use a `StepEvent` to get a CDI bean in a `@Deployment(testable=false)` enviroment?

I need to access a CDI bean in the `Given` phase.

Cheers

**Comment by rmannibucau** [comment]
@aVolpe you are right, I think mixing with arquillian-warp at class level you can achieve it in a more reliable way. Alternative is to write a small @WebFilter/@WebServlet added to the application to map some in container actions
