### ISSUE TITLE
Tomme being downloaded everytime

### ISSUE THREAD

**Issue by rmpestano** [cukespace/cukespace#73]
There is a way to cache downloaded tomee? , What I am experiencing here is that tomee is being downloded everytime I run tests (without clean):

```
INFORMAÇÕES: Unable to find home in: D:\projetos\arquillian\cukespace\examples\target\tomee-remote
ago 30, 2016 4:07:36 PM org.apache.openejb.arquillian.common.MavenCache getArtifact
INFORMAÇÕES: Downloading org.apache.tomee:apache-tomee:7.0.1:zip:webprofile please wait...
```

I see that **target/tomee-remote** is being deleted after tests execution

**Comment by rmannibucau** [comment]
Quite unrelated cukespace but tip is to add tomee artifact (type=zip) as test dependency in the pom this way zip is resolved locally each time.

**Comment by rmpestano** [comment]
:+1:
