### ISSUE TITLE
Support for TestNG

### ISSUE THREAD

**Issue by davigp** [cukespace/cukespace#83]
Hi CukeSpacers!

I'm trying to use cukespace with TestNG, I saw on master (1.6.4-SNAPSHOT) that were included examples for TestNG. My question is if it's possible to use TestNG on previous versions, if not, do you have an estimate date to release version 1.6.4?

Thanks in advances,
Davi Garcia.

**Comment by rmannibucau** [comment]
just released 1.6.4

**Comment by davigp** [comment]
Thanks, I'll test TestNG on the new release!

**Comment by davigp** [comment]
Do you know when it'll be available on https://mvnrepository.com ?

**Comment by rmannibucau** [comment]
Not but it is already available on central, take care mvnrepository is not central
