### ISSUE TITLE
arquillian-junit-standalone scenario execution issue

### ISSUE THREAD

**Issue by davigp** [cukespace/cukespace#84]
Hi Folks,

First, thanks by creating the CukeSpace! I didn't find any other solution like this, and I need this a lots.

I'm facing a bug running cukespace with arquillian-junit in standalone mode.
I'm using last stable cukespace version, v1.6.3, I have tried with the latest version on master today (1.6.4-SNAPSHOT) and seems that this bug is fixed.

Bug descrition: Running CukesInBellyFunctionlaTest in standalone mode the ArquillianCucumber executor, executes the scenario multiple times.

To reproduce the bug I removed all configurations, dependencies and classes that referenced arquillian-junit in container mode, including the src/main directory. So, by replacing one single dependency, arquillian-junit-container with arquillian-junit-standalone you can reproduce this issue.

Follow attached, one patch for the tag cukespace-parent-1.6.3 and another for cukespace-parent master, also printscreens showing the multiple scenario execution issue. 

[patches.zip](https://github.com/cukespace/cukespace/files/740878/patches.zip)

![arquillian-junit-container-ok](https://cloud.githubusercontent.com/assets/6797074/22448809/06f6d808-e743-11e6-8402-b10b4138532d.png)
![arquillian-junit-standalone-issue](https://cloud.githubusercontent.com/assets/6797074/22448810/06fbc246-e743-11e6-81fa-064eea948396.png)

My goal is to report what I faced to help you to avoid this issue on new versions, and ask you again (#83 too ;) about the estimate to release v1.6.4.

I want to be a contributor, perhaps I can help you to fix some issues.

Many Thanks,
Davi Garcia.

**Comment by rmannibucau** [comment]
if i get it right i'm affecting it to 1.6.4 as being fixed, please shout if not

**Comment by davigp** [comment]
You're right, the issue was on 1.6.3, 1.6.4 it's ok.
