### ISSUE TITLE
Impossible to run the example from IntelliJ

### ISSUE THREAD

**Issue by mosser** [cukespace/cukespace#89]
Hi,

I cloned the project, and was able to run the example thanks to maven. an `mvn package` invocation triggers all the scenarios.

However, When importing the project as a maven project in IntelliJ, it is impossible to run the tests. A right-click on the `.feature`  allows me to run the feature test (thanks to the cucumber plugin), but the test fails as it does not find the steps definition.

I also realized on my project that without an `@CucumberOptions(features = "src/test/resources")` annotation on the class that defines the steps, maven will not find it. I'm not sure if the two problems are related.

any hints ?

**Comment by rmannibucau** [comment]
Hi,

first issue is likely related to cucumber plugin which doesn't support cukespace I think
second one can depend the working dir for instance, you can debug in https://github.com/cukespace/cukespace/blob/master/core/src/main/java/cucumber/runtime/arquillian/feature/Features.java#L45 to identify the issue faster

**Comment by mosser** [comment]
ok. Any plans to support IDE plugins?

**Comment by rmannibucau** [comment]
not there until someone wants to contribute it but guess the official plugin can more easily

**Comment by mosser** [comment]
ok, thanks for your answer.
